// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMU81PSY029PKGCCfdI5Upx7bO0lCsv4g',
    appId: '1:759679985277:web:475d79e6a02da8cc787314',
    messagingSenderId: '759679985277',
    projectId: 'readwrite-61165',
    authDomain: 'readwrite-61165.firebaseapp.com',
    storageBucket: 'readwrite-61165.appspot.com',
    measurementId: 'G-37YM44BQW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3neZKQ12o_RtwWoHUKg_4bdiY_YxvNU',
    appId: '1:759679985277:android:8b1086555d92e4ec787314',
    messagingSenderId: '759679985277',
    projectId: 'readwrite-61165',
    storageBucket: 'readwrite-61165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHlzk4MemvcrjVSv413LLzNpSAMIHboo',
    appId: '1:759679985277:ios:266de9b0e6dcbf0c787314',
    messagingSenderId: '759679985277',
    projectId: 'readwrite-61165',
    storageBucket: 'readwrite-61165.appspot.com',
    iosClientId: '759679985277-f7tgsvo9nig3g0sf8egfirdlkbbpkem7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjHlzk4MemvcrjVSv413LLzNpSAMIHboo',
    appId: '1:759679985277:ios:266de9b0e6dcbf0c787314',
    messagingSenderId: '759679985277',
    projectId: 'readwrite-61165',
    storageBucket: 'readwrite-61165.appspot.com',
    iosClientId: '759679985277-f7tgsvo9nig3g0sf8egfirdlkbbpkem7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasee',
  );
}
